/*
 * (Homework 8)
 * Name: Suppatouch Srinual (Nine)
 * ID: 2420210037
 * L8.6: Keyboard.java
 *
 * ==================================================================================
 * Instruction: Write a program using a keyboard event (KeyListener Interface) to
 * immediately convert the value (Temperature) when it is typed. If something other
 *  than a number is typed, display an ERROR MESSAGE.
 * ==================================================================================
 */


import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author USER
 */
public class Keyboard extends javax.swing.JFrame {
    /**
     * Creates new form mainUI
     */
    public Keyboard() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        fahField = new javax.swing.JTextField();
        celField = new javax.swing.JTextField();
        fahrenheitLabel = new javax.swing.JLabel();
        celsiusLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("instantTempConverter");
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        fahField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                fahFieldKeyReleased(evt);
            }
        });

        celField.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                celFieldKeyReleased(evt);
            }
        });

        fahrenheitLabel.setText("Fahrenheit");

        celsiusLabel.setText("Celsius");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(74, 74, 74)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(fahField, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(fahrenheitLabel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 90, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(celField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(celsiusLabel, javax.swing.GroupLayout.Alignment.TRAILING))
                                .addGap(74, 74, 74))
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(121, 121, 121)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fahField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(celField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(fahrenheitLabel)
                                        .addComponent(celsiusLabel))
                                .addContainerGap(135, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void fahFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        String getfText = this.fahField.getText();

        if (!getfText.isEmpty()) {
            if (this.checkAlpha(getfText)) {
                JOptionPane.showMessageDialog(null, "Error!");
                this.returnToEmpty();
            }
            else {
                double fahTemp = Double.parseDouble(getfText);
                double celTemp = (fahTemp - 32.0) * (5.0 / 9.0);

                this.celField.setText(String.format("%.2f", celTemp));
            }
        }
    }

    private void celFieldKeyReleased(java.awt.event.KeyEvent evt) {
        // TODO add your handling code here:
        String getcText = this.celField.getText();

        if (!getcText.isEmpty()) {
            if (this.checkAlpha(getcText)) {
                JOptionPane.showMessageDialog(null, "Error!");
                this.celField.setText("");
                this.returnToEmpty();
            }
            else {
                double celTemp = Double.parseDouble(getcText);
                double fahTemp = (celTemp * (9.0 / 5.0)) + 32.0;

                this.fahField.setText(String.format("%.2f", fahTemp));
            }
        }
    }

    private void formWindowOpened(java.awt.event.WindowEvent evt) {
        // TODO add your handling code here:
        this.setLocationRelativeTo(null);
    }

    private boolean checkAlpha(String text) {
        boolean isAlpha = false;
        for(int i = 0; i < text.length(); i++) {
            if (!Character.isDigit(text.charAt(i))) {
                if (text.charAt(i) == '.') {
                    continue;
                }
                isAlpha = true;
                break;
            }
        }
        return isAlpha;
    }

    private void returnToEmpty() {
        this.fahField.setText("");
        this.celField.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Keyboard.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Keyboard().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify
    private javax.swing.JTextField celField;
    private javax.swing.JLabel celsiusLabel;
    private javax.swing.JTextField fahField;
    private javax.swing.JLabel fahrenheitLabel;
    // End of variables declaration
}
